### ISSUE TITLE
Variable with quotes around are recognized as strings

### ISSUE THREAD

**Issue by rugk** [footballhead/language-batch#15]
![variablewithquotes](https://cloud.githubusercontent.com/assets/11966684/9301655/5a371008-44d0-11e5-8c5c-6c4939e36e5b.PNG)
![variablewithquotes2](https://cloud.githubusercontent.com/assets/11966684/9301699/b60c2fd0-44d0-11e5-9c0c-a6c6dd7b9c84.PNG)

But this works as expecting: (I assume because it does not detect it as a string
![variablewithquotes3](https://cloud.githubusercontent.com/assets/11966684/9301711/cb9aed64-44d0-11e5-99c0-63d775e0d020.PNG)

**Comment by footballhead** [comment]
Given the sunset of [Atom](https://github.blog/2022-06-08-sunsetting-atom/), this project is no longer being maintained.
