### ISSUE TITLE
Other %0-like variables not recognized

### ISSUE THREAD

**Issue by rugk** [footballhead/language-batch#16]
These variables are correctly recognized:

```
set test=%0
if "%test%"=="example" goto example
set test=%~0
if "%test%"=="example" goto example
set test=%~D0
if "%test%"=="example" goto example
set test=%~DP0
```

![batchokay](https://cloud.githubusercontent.com/assets/11966684/9301558/a61f8582-44cf-11e5-92a8-8ad387578c9d.PNG)

So far that's okay, but this one is not recognized correctly at all:

```
set test=%~DP0
if "%test%"=="example" goto example
rem %
```

![batchbadvariable](https://cloud.githubusercontent.com/assets/11966684/9301876/2603628a-44d2-11e5-97d7-d8abfab53526.PNG)
However this is valid batch as you can also combine the different sets of variables.

A kind of stupid workaround would be is this:

```
set test=%~DP0
rem % (workaround...)
if "%test%"=="example" goto example
```

![batchbadvariableworkaround](https://cloud.githubusercontent.com/assets/11966684/9301793/6ddb299a-44d1-11e5-9517-00ed6a560f60.PNG)

**Comment by rugk** [comment]
It seems they are recognized as a normal %variable% - which is of course crap. And additionally a %variable% also can't be split in multiple lines.

**Comment by footballhead** [comment]
Given the sunset of [Atom](https://github.blog/2022-06-08-sunsetting-atom/), this project is no longer being maintained.
