### ISSUE TITLE
Missing Commands

### ISSUE THREAD

**Issue by lnx00** [footballhead/language-batch#23]
'type' and 'mode' currently aren't highlighted.
And after 'echo' nothing should be highlighted.

Here's also a screenshot:
![btachbug](https://user-images.githubusercontent.com/34384416/37225863-51a22330-23d8-11e8-92fe-30d5aa4030a2.PNG)

**Comment by footballhead** [comment]
Given the sunset of [Atom](https://github.blog/2022-06-08-sunsetting-atom/), this project is no longer being maintained.
