### ISSUE TITLE
Keywords following ECHO are still highlighted

### ISSUE THREAD

**Issue by footballhead** [footballhead/language-batch#9]
See this example:

![echo](https://cloud.githubusercontent.com/assets/3687359/3588113/c2879328-0c3f-11e4-912f-7644d2c53bb1.png)

**Comment by rugk** [comment]
:+1: Yes this looks really funny. 
And in this case it even detects the rem and makes stupid things:
![echobugrem](https://cloud.githubusercontent.com/assets/11966684/9301605/ff1539f2-44cf-11e5-9779-958915552903.PNG)

**Comment by rugk** [comment]
I mean the cause of this is that comments in Batch can only start at the first line...

**Comment by SergioRebelo-TalkDesk** [comment]
Hey @footballhead , is there any chance for this to be updated/fixed?
Thanks in advance.

**Comment by footballhead** [comment]
Given the sunset of [Atom](https://github.blog/2022-06-08-sunsetting-atom/), this project is no longer being maintained.
